name: Python checks

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check code formatting with black
        run: |
          pip install black
          # stop the build if the code is not properly formatted
          black --line-length 140 . --check -t py37
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics --exclude=venv  --max-line-length=140 --select=C,E,F,W,B,B950 --ignore=E203,E501,W503
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Type checking with mypy
        run: |
          pip install mypy
          mypy run.py run_cmd.py --ignore-missing-imports
